name: Deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 161.22.42.207
          port: 22
          username: wachi
          key: ${{ secrets.PLATITA }}
          script: "cd /var/www/html/platita; git pull origin main; sudo service php8.3-fpm reload"